### ISSUE TITLE
swipe can bounce and submit the opposite answer

### ISSUE THREAD

**Issue by camallen** [zooniverse/mobile#128]
I noticed when using snapshots at sea on mobile app that the swipe can bounce of the swiped direction and submit the opposite answer. Not sure what the specifics are but from memory it was fast / vigorous swipes maybe with a pre-release before hitting the submission point on the edge. 

Happy to help debug this, if some have ideas.

**Comment by noahmalmed** [comment]
Will keep this open because this sounds sporadic and difficult to reproduce, but upon some investigation I was not able to reproduce

**Comment by camallen** [comment]
I have reproduced this today (android 7.0 i assume latest version of the app). 

If you start a swipe and "let go" (lift finger) before it reaches the edge it can bounce back to the middle and in some cases back to the other side for submissions. Swiping to a top corner and releasing early is a neat way to show the bounce of a side.

Side note, it would be nice to report the app version and possibly the OS in the app somewhere for easy debug reports.

**Comment by noahmalmed** [comment]
Thanks @camallen! Will also look into bug reporting

**Comment by noahmalmed** [comment]
This has been fixed
