### ISSUE TITLE
Repeated project tutorials

### ISSUE THREAD

**Issue by astopy** [zooniverse/mobile#130]
The tutorial for Camera Catalogue opens almost every time I open the project. I assume the app isn't updating the user project preference to record that the tutorial has already been completed.

**Comment by eatyourgreens** [comment]
Can you have a look at your user project preferences in the Chrome dev tools, and see if anything is set for this project and workflow?

It may also be that the tutorial is running before the UPP response from the API.

**Comment by astopy** [comment]
```
            "preferences": {
                "selected_workflow": "4403",
                "tutorials_completed_at": {
                    "54": "2016-07-07T09:16:22.597Z",
                    "734": "2017-08-03T09:16:10.291Z",
                    "761": "2017-08-02T13:19:08.160Z"
                }
            },
```

I think you're right that it's displaying the tutorial before it receives the UPP. It only displays the tutorial the first time I open the project after opening the app, and in this case the project has a choice of two active workflows and it only displays the tutorial for the first one I select.

**Comment by eatyourgreens** [comment]
I don't know the workflow ID for that Camera Catalogue workflow, off the top of my head, but it does look like your profile has recorded that you've completed all the available tutorials.

So the mobile app must not be waiting for the preferences to download, or update, before checking `tutorials_completed_at[workflow_id]`.

**Comment by wgranger** [comment]
@astopy I'm having trouble replicating this issue, but I have an idea of a way to fix what you're experiencing. Just to confirm, you are logged in when experiencing this? Also, although it probably won't make much of a difference either way, are you using Android or iPhone?

**Comment by astopy** [comment]
Yup, I'm logged in. I'm using an iPhone.

**Comment by noahmalmed** [comment]
@wgranger did anything come of this, or is it still outstanding?
