### ISSUE TITLE
swipe workflow with Grid 2col not properly displaying multiple images

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/mobile#133]
swipe enabled workflow with multi-image options - separate, Grid 2col - the second image is not displayed.

this was determined with the PRN Y/N workflow when the before image would show, but the after image would not.

**Comment by noahmalmed** [comment]
Do we even want to allow multi-image subjects in mobile

**Comment by mcbouslog** [comment]
Good question. I opened this as we were attempting to get a Planetary Response Network yes/no workflow working in the app. Now, I'm in favor of closing this specific issue, and deferring to the general planning that's happening.
