### ISSUE TITLE
Setting up test/staging environment

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#135]
We are currently deving in the production environment, we should set up some mobile friendly projects in the staging environment.

**Comment by wgranger** [comment]
Agreed, and more apparent when doing code reviews. Also, we should adjust the redirect into webview (from a project list on the app) to direct to the staging site instead of getting the same (project cannot be found, etc.) error when redirecting to zooniverse.org from a staging project.

**Comment by noahmalmed** [comment]
Closing because not really an issue
