### ISSUE TITLE
Minor TypeError

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#141]
This came about when I was testing #139 (although not related to that code) in Android Studio. It's a minor type error that can prob be solved with a line of code. Non-breaking, but will prevent this from appearing in the future.

<img width="225" alt="screen shot 2018-02-06 at 12 04 08 am" src="https://user-images.githubusercontent.com/14099077/35867097-87cf4140-0b1e-11e8-8c91-e1b29cfc4a07.png">

**Comment by wgranger** [comment]
Forgot to mention. The only thing I did differently was that I was checking state changes in the Redux devtools by going to settings and toggling some notifications (w/ iOS). Then I opened Android and received this.

**Comment by noahmalmed** [comment]
was fixed in #150
