### ISSUE TITLE
Sign In screen: Continue without signing in

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#148]
Continue without 'signing in' becomes unhighlighted if text in text fields. 

Should just stay highlighted

**Comment by beckyrother** [comment]
This also needs a Back button `<` in the top left nav bar when you come to this page from `Sign In / Register` in the hamburger menu. Back should take the user back to whatever page they were last looking at.

**Comment by noahmalmed** [comment]
To get started on this, I would check out `SignIn.js`

**Comment by chelseatroy** [comment]
This doesn't happen anymore.
