### ISSUE TITLE
update workflow request

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/mobile#151]
https://github.com/zooniverse/mobile/blob/master/src/actions/index.js#L148

update the workflow request from:
```
return project.get('workflows', {page_size: 100, active: true})
```
to:
```
return project.get('workflows', {active: true, fields: 'display_name,configuration', mobile_friendly: true})
```

**Comment by noahmalmed** [comment]
The reason we want to make this change is because we are changing how we mark mobile workflows. Instead of using the `swipe_enabled` configuration in workflows, we want to use the `mobile_friendly` attribute.

**Comment by noahmalmed** [comment]
This means as a part of this issue, we need to 
1) Make sure our back-end is groomed correctly (all `swipe_enables` are switched to `mobile_friendly`)
2) Change project code from grabbing all mobile friendly projects, but to also grabbing all project with mobile_friendly workflows.

**Comment by mcbouslog** [comment]
on point 2, I think we just need to update https://github.com/zooniverse/Panoptes-Front-End/pull/3894 so both `project.mobile_friendly` (the PR already does this) and `workflow.mobile_friendly` are approriately toggled together, but I don't think any code related to the projects request in this repo needs to be updated.

**Comment by mcbouslog** [comment]
I manually updated the following currently active or incomplete `configuration.swipe_enabled: true` workflows to also be `mobile_friendly: true`:

1. Camera CATalogue - Empty or Not, 4403
2. Camera CATalogue - Vehicle or Not, 4636
3. Floating Forests - Kelp presence/absence, 3246
4. Snapshots at Sea - Yes/No (Q2), 433
5. Snapshots at Sea - Yes/No (Q3), 505
5. Planet Four: Ridges - Meridiani Ridges Workflow, 5376

**Comment by mcbouslog** [comment]
updated suggested API request with `fields` param, I think those are all the fields that'll be needed, but not entirely sure.

I'm not sure how to handle [`isValidSwipeWorkflow`](https://github.com/zooniverse/mobile/blob/master/src/actions/index.js#L171). we could include the tasks attribute in the API request, though that somewhat defeats the purpose of editing the API request to the response is smaller. though if a workflow is `mobile_friendly: true` and we're already filtering on that, the `tasks` will be small.

curious what @wgranger or @camallen think

**Comment by camallen** [comment]
> we could include the tasks attribute in the API request, though that somewhat defeats the purpose of editing the API request so the response is smaller. though if a workflow is mobile_friendly: true and we're already filtering on that, the tasks should be small.

I think with the filtering it should be fine to request tasks here. I assume the workflow tasks are question only and yes/no?

**Comment by noahmalmed** [comment]
I'm torn on this. 

For now, it's no big deal that we are pulling down tasks, because these workflows are curated and manually selected to be mobile flows. But in the future, my hope is to open the door for more types of workflows and potentially more complicated workflows, which could start posing a problem with pulling in all of the tasks all at once.

**Comment by noahmalmed** [comment]
I guess probably in this future, the `mobile_friendly` attribute wouldn't be useful anymore, so we would probably have to make code changes anyways. So for now I think we should filter to include tasks

**Comment by eatyourgreens** [comment]
To be honest, the checks in [`isValidSwipeWorkflow`](/zooniverse/mobile/blob/master/src/utils/is-valid-swipe-workflow.js) all look like they could be carried out in the project builder, when the workflow is modified, with the true/false result being saved as a flag on the workflow config.

I'm inclined to come down on the side of only loading the task when you need it ie. in the classifier.

**Comment by noahmalmed** [comment]
So we have a `mobile_friendly` attribute and a `isValidSwipeWorkflow` config flag? Personally, I would prefer the app to implicitly figure out what kind of UI it should display. This way we can build out a native ui while requiring minimal work from the back-end or PFE

**Comment by eatyourgreens** [comment]
In that case, could the `isValidSwipeWorkflow` check be deferred until after I've picked a workflow, since it requires the full workflow to be loaded in order to inspect the tasks?

**Comment by noahmalmed** [comment]
Oh I see why this is an issue. No matter whether we do it in project builder or on the mobile side, we will have to load workflows config. Perhaps it would just be best to consider the `mobile_friendly` attribute to also mean `isValidSwipeWorklow`? 

Talking to @wgranger it sounds like there is some criteria around when a user would be allowed to make a flow mobile friendly or not. I'm not sure if that criteria lines up with what we are checking on the mobile side.

**Comment by wgranger** [comment]
Those criteria should be the same on the mobile and PFE/project builder side, so it's pretty safe. The criteria includes that the project is launch_approved and the workflow:
- Has one task
- Has two available answers
- Questions has less than 200 characters
- Has less than three shortcuts/unlinked tasks
- Cannot be a flipbook
- Cannot provide feedback

**Comment by noahmalmed** [comment]
In that case, as long as we don't manually go in and change things. We can safely remove the client-side check and trust that a workflow being mobile friendly also means that it is swiper valid

**Comment by camallen** [comment]
Looks like any user can update their project / workflow to be `mobile_friendly` via the API. should we admin protect these attributes? How are they meant to be set by a user in the lab? the checkbox is greyed out till certain conditions are met?

**Comment by noahmalmed** [comment]
I believe so, @wgranger would know for sure the behavior? I think we do want to admin protect this attribute, at least until we have less rigid rules around what is allowed to go on mobile.

**Comment by wgranger** [comment]
The checkbox is greyed out until certain conditions are met, yes. Project builders should be able to toggle the box to add the workflow to the swipe classifier. That toggle box will also set both the project and workflow to `mobile_friendly: true`, so I don't think we should admin project this.

**Comment by noahmalmed** [comment]
I'm not sure I'm following: shouldn't we not allow users to modify the mobile friendly attributes because we have strict rules for what they mean?

**Comment by wgranger** [comment]
We have the strict rules in place to keep users from doing this randomly. However, this aim of [this pr](https://github.com/zooniverse/Panoptes-Front-End/pull/3894) is to allow users/project builders to add their workflow to the swipe classifier/app.

If anything, we could possibly allow the project and workflow to be toggled `mobile_friendly: true` only if the project is `launch_approved`.

**Comment by noahmalmed** [comment]
@wgranger talked offline and I agree that this should not be admin protected. I was just  misunderstanding what that meant!

**Comment by camallen** [comment]
happy with the decision you've made, just not that i can set my workflow via the api and skip all these checks if I want to.

**Comment by noahmalmed** [comment]
Is there a way to admin protect an attribute on the console?

**Comment by wgranger** [comment]
Gotcha. That was part of the reasoning for having the checks within the mobile app as well. Even if a workflow gets set to `swipe_enabled: true`, it won't show up in the app unless it meets the criteria. 

In the case someone marks a workflow `mobile_friendly` or `swipe_enabled` that shouldn't be, it would show up in the webview (Safari) rather than the app itself.

**Comment by noahmalmed** [comment]
I mean, because this is such a corner case. We could remove the client side checks for filtering and do them when we attempt to load the classification screen. 

If it turns out that the `mobile_friendly` has been tampered with, we just load the webview instead.

The only problem is that the user will receive some deceiving UI

**Comment by camallen** [comment]
Sounds like the combination of these attributes will work then, long term we should think about pushing this API side and automating the process for native app availability.
