### ISSUE TITLE
Modify CI, so it can actually deploy test builds

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#155]
Looks like the CI for the app just runs the test suite and does some static linting.

It would be nice to actually make a build with each merge to master, so deploying and beta testing is more streamlined

**Comment by camallen** [comment]
@noahmalmed normally we use dockerhub (linked up via webhooks) to build a new image after a merge to master, in some instances we do use Travis CI to build and push a new image after tests pass as well. @astopy can help you sort this.

**Comment by astopy** [comment]
The iOS build will need to happen in macOS with Xcode I think, so I'm not sure how we can automate that at the moment. Unless there's a hosted service that can do it?

**Comment by noahmalmed** [comment]
Travis lets you run CI in macOS: https://docs.travis-ci.com/user/reference/osx/ ! So we should be able to make builds for it. As mobile repo is already hooked up to travis it may not be that difficult.

Anyways, I don't think this is super important because we only have one dev working on this at the moment, but it was just something I wanted to look into when I had some time.

**Comment by astopy** [comment]
Great, if we can do it with Travis that'll certainly make things easier.

**Comment by lcjohnso** [comment]
closing, see #377 and #378
