### ISSUE TITLE
Zoom by pinching

### ISSUE THREAD

**Issue by denslowm** [zooniverse/mobile#157]
Our project (Notes from Nature) would like to be able to zoom into an image by "pinching" on the screen (not just tapping). I believe that this was the previous functionality. 

It is currently not working on Android version 1.1

We tried enabling Pan and Zoom, but that didn't work.

**Comment by noahmalmed** [comment]
Thanks for bringing this to our attention @denslowm. Pan and Zoom is the correct setting to enable this on the app. I tried this on our end on a test project on an Android and everything seems to be working correctly.

Can you just clarify a couple of things for me before I investigate this in more depth:

1. Can you make sure that you restart your app (kill it and re-open) after you have enabled Pan and Zoom
2. Make sure that you first tap the image and then try to pinch and zoom once it has expanded.

**Comment by denslowm** [comment]
Thanks, we had to launch workflow in question, but I can confirm that these steps did not work.

We just got a black screen when we tapped on the image and it never loaded. This happened when Pan and Zoom were on and off. I am happy to set up a new test project on Notes from Nature to do more testing with you. We are really excited to get an app based expedition launched ASAP.

**Comment by noahmalmed** [comment]
Thanks for more details. After some further investigation, I was able to reproduce this bug. I'll keep you updated as I make progress with this.

**Comment by denslowm** [comment]
I assume this requires an update submitted to Apple/Google. Is that correct? If so, can we test it before it's submitted?

**Comment by noahmalmed** [comment]
@denslowm You are correct. I am going to leave this open until we actually release to the Apple/Google so you know when you can test it out.
