### ISSUE TITLE
Z-index problems

### ISSUE THREAD

**Issue by robgur** [zooniverse/mobile#160]
When I tested the Android version of the app for our Notes from Nature expedition, I would often get a blank white box instead of the next image.  This basically meant I had to restart the app.

**Comment by noahmalmed** [comment]
@robgur I believe this is the same issue as #157. Is so, I would like to close this issue and just track it on one thread

**Comment by robgur** [comment]
Different issue I think.  Michael, can we test a new mobile phenology
expedition and see if both are fixed simultaneously?

**Comment by denslowm** [comment]
I would like to do that. Is there a way for me to test it before submission to Apple/Google? I would hate to wait for that and then find out we have more issues.

**Comment by robgur** [comment]
Isn't there a test tool for mobile apps.

**Comment by noahmalmed** [comment]
We currently have plans to build a test tool into the mobile app, but it does not exist yet. 

The best we can offer you now is adding you as a tester for our app on google play. This will allow us to release a beta test build to the app store which only you (and anyone else on the test list) will be able to download. Then you should be able to turn on the project and test to make sure that it works. 

If everything is working correctly, we can release to the whole app store. If not, we turn off your project and I go back to working on the bug.

**Comment by robgur** [comment]
That is acceptable.  Please let us know when there is a new beta.

**Comment by denslowm** [comment]
Agreed. I assume you need our Google credentials. Feel free to PM for that.
Thanks!

**Comment by noahmalmed** [comment]
Great! There are a few more things I want to get into the release, I am targeting for mid next week. I'll PM you guys for your credentials when I'm ready to release

**Comment by robgur** [comment]
Awesome!
