### ISSUE TITLE
Add google analytics for classifications

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#172]
Fix pending NSF grant

**Comment by noahmalmed** [comment]
Also as a part of this, we need to migrate to google analytics new platform. Per this email from google: 

> Dear Google Analytics customer,
> 
> You are receiving this email because you are in the first wave of customers who have been identified as users of the older style of Google Analytics for mobile apps reporting and the Google Analytics Services SDK. Specifically, we are notifying you regarding your Google Analytics property(ies) (, ID: UA-1224199-62: "Zooniverse Mobile").
> 
> We want to let you know that in October 2019 we will begin to sunset our Google Analytics for mobile apps reporting and the Google Analytics Services SDK. We are investing our resources in the latest style of app reporting in Google Analytics that works in conjunction with Firebase – Google's integrated app developer platform. As such, the following will take place:
> 
> In 2019, we will begin to decommission properties that receive data exclusively from the Google Analytics Services SDK.
> Data collection and processing for such properties will stop on October 31, 2019.
> Reporting access through our UI and API access will remain available for these properties' historical data until January 31, 2020.
> After our service is fully turned down, these properties will no longer be accessible via our Google Analytics UI or API, and their data will be removed from Google Analytics servers. You will receive further notification when this time nears.
> At this time, no Analytics 360 properties are impacted by these changes.
> 
> We want to give you plenty of time to make the transition. The good news is that the latest solution using the Firebase SDK is even more intuitive and includes free and unlimited event reporting to meet the needs of app-centric businesses. We've invested heavily to make this solution best-in-class, with new features and capabilities rolling-out continually. Additionally, our offering is closely integrated with other Google products and features to help grow your app business like Crashlytics, AdMob and Remote Config.
> 
> Getting started with our latest app reporting features is simple and straightforward. Here's how. For additional information on our new Google Analytics app reporting, visit the Help Center.
>

**Comment by lcjohnso** [comment]
Closing -- now see #413
