### ISSUE TITLE
Change wording for "beta"

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#173]
This can be confused with the "beta" launch of a project, where volunteers will give the project a test run. Instead, the terminology might be better changed to "preview" or something of the sort.

**Comment by noahmalmed** [comment]
@beckyrother thoughts on this? Maybe something like 'Your Projects'

**Comment by noahmalmed** [comment]
I'm nervous preview is a little too vague? What about "Development" it matches up with the language in project builder as well

**Comment by beckyrother** [comment]
Hmm. Is "Project Preview" or "Preview Project" too long? I like how "Preview" implies that it's not live yet

**Comment by noahmalmed** [comment]
Maybe too long. The more I think about the happier I am with Preview

**Comment by wgranger** [comment]
Closed with #169
