### ISSUE TITLE
Remove/rethink the coloring that happens when swiping 

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#175]
I'm talking about this type of coloring:
![simulator screen shot - iphone 6 - 2018-04-10 at 13 32 18](https://user-images.githubusercontent.com/10929131/38741756-91761d3e-3f32-11e8-8a16-e0fcdab6f101.png)

I think it should be an option for the user to swipe between two different options besides "Yes" and "No", like "Spiral" and "Disk" or something. I think we should rethink the the colored feedback we show the user when they swipe in a direction (left is always red and right is always teal).

@beckyrother thoughts?

**Comment by beckyrother** [comment]
That's a great idea. Did you have another color in mind? Or just remove it in general?

**Comment by noahmalmed** [comment]
I think remove the color. I'm nervous that that won't be enough feedback though. Here is what is would look like with no color
![simulator screen shot - iphone 6 - 2018-04-16 at 14 08 57](https://user-images.githubusercontent.com/10929131/38829802-d9222a16-417f-11e8-8a11-cc45d71fc48b.png)

**Comment by noahmalmed** [comment]
Just spitballing here: 
We could give the buttons different colors (more neutral) and fade the corresponding color?

**Comment by beckyrother** [comment]
I'm looking at some inspiration sites, and a lot of them don't actually change the color – https://cdn-images-1.medium.com/max/1600/1*edOD5tzy5v5DUc5Uz8gZuA.gif Maybe something like that?

**Comment by noahmalmed** [comment]
Interesting... no feedback at all actually looks pretty good

**Comment by beckyrother** [comment]
I like the type on top of the image to show that something is happening at least, but maybe that's all we need?

**Comment by beckyrother** [comment]
Here's a crazy interaction that may be Too Much for us, but something kind of related to our unconference discussion last week: https://dribbble.com/shots/2913888-Thaw-Interest-level-selector

**Comment by noahmalmed** [comment]
That's super cool! Interesting to think how it can be used. But yeah, I would be happy to remove the color overlay and just leave the text overlay
