### ISSUE TITLE
Show some sort of loading feedback when images are loading

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#179]
We currently don't give the user any sort of feedback when a subject is loading.

This can lead to two bad scenarios:
1) Neither image load and the user just sees a large patch of white space on their screen.

2) The back image loads before the front and the user will try to classify the back image.

These scenarios are both pretty bad (especially number two). I think we need some sort of feedback to the user that images are loading.

Maybe just be as simple as putting a placeholder image where the subject image should be.

@beckyrother any ideas?

**Comment by beckyrother** [comment]
Agreed @noahmalmed . I think we have a loading spinner that's used elsewhere – would that be appropriate here as well?

**Comment by noahmalmed** [comment]
![imagesloading](https://user-images.githubusercontent.com/10929131/39769553-25667466-52b2-11e8-818e-2c42bb042ea8.gif)

Here's a gif of what images loading often looks like in the app. The blank screen is when both images are loading, the next screen is when the back image has loaded and the front hadn't loaded yet, the last screen is both images loaded. 

I think putting up a loading spinner over the screen while both images load isn't a great solution because it may be disrupting.

Maybe some sort of placeholder gif or animation, even a spinner, where the image is loading would be enough.

**Comment by noahmalmed** [comment]
![loading_example](https://user-images.githubusercontent.com/10929131/40685848-f77bd4e2-635a-11e8-845e-1254a996dc72.gif)

@beckyrother Here's a prototype for

**Comment by beckyrother** [comment]
This looks great! Just use Karla for the loading text so it looks the same as that first spinner.
