### ISSUE TITLE
Beta Mode displaying non-native projects

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#209]
If a project is marked as mobile-friendly but doesn't have any mobile-friendly workflows it will still show in the beta list. 

For Beta Mode, we should just only display "Made for Mobile" projects. That is projects with mobile friendly workflows

**Comment by noahmalmed** [comment]
To fix this, I would check out `actions/projects.js`

**Comment by lcjohnso** [comment]
Removed non-mobile projects from app
