### ISSUE TITLE
Drawing Bug

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#211]
Currently, if a user tries drawing on an image and the tool goes off the image, the mark tends to jump a bit. It's probably a simple math bug somewhere. 

This isn't the worst bug, as a user shouldn't be moving the tool off screen, but it's not ideal. I'd be fine opening an issue about it and making a fix in a future PR, or adding another commit to this one.

_Originally posted by @wgranger in https://github.com/zooniverse/mobile/pull/210#issuecomment-431454600_

**Comment by wgranger** [comment]
I should note that this appears to only happen in Android.
