### ISSUE TITLE
Something is wrong with Push Notifications

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#213]
It seems like there is something wrong with push notifications. The notifications send out to about half of the people on the team who were subscribed to the content.

My guess is that the app somehow gets in a bad state and unsubscribes users automatically. Not really sure until further investigation is done.

**Comment by noahmalmed** [comment]
I'm pretty sure the issue with this is that the code subscribes to firebase topics before getting a token from firebase. It's important that we receiver the token from firebase before subscribing to topics. Otherwise the subscription won't be linked to the device

**Comment by noahmalmed** [comment]
A fix is out for this in production, waiting to see if the fix solves the issue when we send out a push notification

**Comment by lcjohnso** [comment]
Closed by #241 and see #414
