### ISSUE TITLE
Font resize issue on Android (possibly also iOS)

### ISSUE THREAD

**Issue by noahmalmed** [zooniverse/mobile#236]
![img-20190124-wa0000](https://user-images.githubusercontent.com/10929131/51701796-d8f6e680-1fd7-11e9-9dd8-25655acfd270.jpg)

When font is increased on the OS there are some layout issues in the app. It's probably worth doing an audit of both apps to see if this bug is showing up elsewhere

**Comment by lcjohnso** [comment]
No issue persists in version 2.11, similar to #451 ; closing.
