### ISSUE TITLE
Workflow Selection: making mobile-only workflows

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#246]
This is a mobile-centric feature request, but probably is largely a PFE issue.

For projects with multiple workflows (e.g., simple yes/no swipe task optimized for mobile and more complex drawing task optimized for desktop), there are cases where we want to limit the mobile-optimized workflow to work **_only_** on the app, **_not_** in the browser/desktop.  For instance, classification quality may vary significantly between desktop and mobile, so it might be best for data analysis to exclude web users from working on mobile-optimized workflows where there responses would need to be treated differently.

A proposed feature to accomplish this: adding additional logic that removes mobile-enable workflows from the web version's workflow options.

A simple solution: adding a follow-up question asking "Allow mobile enabled workflow in browser classifier?" (second tic box on the PFE workflow page) that essentially removes the mobile-enabled option from the sample of available workflows, making it only visible to the mobile app.

Another solution: this decision could also be implemented as a more general purpose follow-up question to the "Allow volunteers to choose their own workflow?" that asks "If false (volunteers assigned to workflow), assign only to default workflow?".  Here, project builders could define a non-mobile workflow as default, and web volunteers would only be routed to this choice.  This option might have the advantage of working within the current workflow selection logic and could be of use beyond this application to limiting access to mobile workflows.  However, this solution only solves the problem of excluding mobile-enabled workflows from the web classifier in the case where a single default workflow for web users is acceptable, and fails if builders still want volunteers to be able to choose from multiple workflow options (just not the mobile-enabled one).

**Comment by noahmalmed** [comment]
Great idea @lcjohnso! This is definitely something we've been discussing over here.

**Comment by noahmalmed** [comment]
To achieve this, we would require some sort of backend change. Either add another property to the workflow model that is something like `mobile-active` or add a flag in a workflows meta data.

Once the back end has changed, the mobile changes should be minimal in `actions/projects.js`

**Comment by srallen** [comment]
Typically we suggest researchers to use the `user_agent` in the metadata to distinguish between the device and browser used during classification. The mobile app also records that it is from the app: https://github.com/zooniverse/mobile/blob/master/src/actions/classifier.js#L94

What would stop researchers now isolating classifications by user agent for separate analysis?

**Comment by eatyourgreens** [comment]
> For instance, classification quality may vary significantly between desktop and mobile, so it might be best for data analysis to exclude web users from working on mobile-optimized workflows where there responses would need to be treated differently.

That's an interesting question. Has anyone ever analysed classification quality to see if it depends on user agent or viewport dimensions? Both of those should be recorded with each classification.

**Comment by lcjohnso** [comment]
Hi @srallen -- You are correct that the information is available to isolate and treat app vs. browser users differently during data analysis, but properly combining sets of classifications made using two very different interfaces could become complicated.

But beyond the analysis considerations, a point that I didn't make in my original comment that is really my main driver here: in my specific use case (Local Group Cluster Search), I'd rather have all users contribute whenever possible through the normal browser-based drawing workflow rather than a simplified mobile-friendly workflow.  The mobile workflow does not serve a separate purpose, but rather is the "lite" version that can be done using a phone app.  Therefore, I would like to enforce this preference for the full drawing task whenever possible -- hence my desire to eliminate the choice on the project's browser homepage.

My hope is that by including a mobile workflow I can attract additional classifications, and even if each simplified yes/no mobile classification is slightly less useful than a browser-based drawing classification, the inclusion of a mobile workflow will still be a net positive due to the ability to attract volunteers/effort through the app that I couldn't reach otherwise.

**Comment by adammcmaster** [comment]
> My hope is that by including a mobile workflow I can attract additional classifications, and even if each simplified yes/no mobile classification is slightly less useful than a browser-based drawing classification, the inclusion of a mobile workflow will still be a net positive due to the ability to attract volunteers/effort through the app that I couldn't reach otherwise.

My hunch is that forcing desktop users to the more complicated workflow will _reduce_ classifications, because you'll lose anyone who only wants to do a simple task and is put off by the more complicated one.

**Comment by eatyourgreens** [comment]
We should remember that phones have browsers too, so even with the more complex workflow you'd have to control for viewport size or user agent to check that the device isn't introducing some sort of bias to the classifications.

I doubt that it is, but I don't know if anyone has actually looked at that.

**Comment by srallen** [comment]
I would suggest we get a data analysis of classifications, both source and quality compared to source before any decision on filtering availability of workflows happens on desktop. I agree with the hunch that preventing desktop users from accessing a simple task workflow would potentially decrease classifications and participation. We have a wide variety of users from children, to classrooms, to people with disabilities. Perhaps someone who isn't comfortable with a mouse would like to participate but can't do drawing tasks. There's a lot of variability here and we need data before doing a UI change that would potentially limit access to participation. 

We usually suggest the simple yes/no tasks to be an initial filtering workflow to be useful for the project, so that's something to consider.

**Comment by srallen** [comment]
Also, I wanted to say about this:

> properly combining sets of classifications made using two very different interfaces could become complicated.

Caesar could help with a lot of the automation and decision making for classifications depending on specifically what it is you want to do.

**Comment by chelseatroy** [comment]
So, provided we decide to make this change, the mobile app isn't really where it would be made. Rather, PFE would either filter out projects that are approved for mobile, or would filter out projects based on some new categorization like mobile-only.
