### ISSUE TITLE
Markdown in app tutorial doesn't seem to render correctly

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#255]
Example - look at https://www.zooniverse.org/projects/etymstra/grouse-grooves/classify tutorial in a browser versus tutorial in the app swipe workflow. ## Are there birds? ## ---- is the first thing you see in the app tutorial, with strange spacing, etc.

**Comment by lcjohnso** [comment]
No issue persists in version 2.11, likely due to #464; closing.
