### ISSUE TITLE
General Items to Address After Upgrade

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#259]
After our most recent RN upgrade, there are several low-priority items that need to be addressed on the app. 

- Tests are running rather slow, and it takes about a minute to run several tests
- We need to address the RN warnings of items that will soon be deprecated to avoid issues with a future RN migration
- The README can be updated to include `react-native run-ios` as a valid command to run the app.

**Comment by lcjohnso** [comment]
Closed by #260 and follow-on RN updates
