### ISSUE TITLE
Items to address

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#264]
- [ ] Don’t see Radio Meteor Zoo ( https://www.zooniverse.org/lab/2471/workflows/11436 ; even though 'enabled on mobile in Project Builder UI), but maybe there’s a reason that still doesn’t show up?

- [ ] Don't see 'Unearthing Ecological Data...' , even though enabled on mobile in Project builder ui (https://www.zooniverse.org/lab/4982/workflows/8389). 

- [ ] Don't see Floating Forest 'kelp on the edge', even though enabled on mobile in Project builder ui https://www.zooniverse.org/lab/2864/workflows/11268

- [ ] Euclid - challenge of the machines shows up twice

- [ ] Classification count incorrect (perhaps related to https://github.com/zooniverse/Panoptes/issues/3146)

**Comment by trouille** [comment]
Note - both Radio Meteor Zoo and Floating Forest have a lot of subject sets. Perhaps that's causing the problem for both of those projects?

**Comment by trouille** [comment]
@beckyrother For a next iteration - on Android, for a project like 'Unearthing Ecological Data' , the light teal with white writing on top for the answer choices can be a little hard to see in sun. Any chance that teal could be a little darker or some other choice?

**Comment by beckyrother** [comment]
@trouille Yes, I'd love to do a design audit and make visual changes like that for both Android and iOS. When you find places that need improvement would you mind posting screenshots here as well?

**Comment by trouille** [comment]
moving design questions from here into https://github.com/zooniverse/mobile/issues/268

**Comment by trouille** [comment]
Note - radio meteor zoo now showing up (because of fixed pagination for projects and workflows)
