### ISSUE TITLE
Support default frame of multi-frame subjects?

### ISSUE THREAD

**Issue by simensta** [zooniverse/mobile#277]
Is it possible for the mobile app to display just the default frame (as indicated by subject metadata) of a multi-image subject?

Use case: A project uses the mobile app to filter subjects into new subject sets for a more complex non-mobile workflow. The more complex workflow requires multi-image subjects.

cc: @hspiers

**Comment by lcjohnso** [comment]
Closing -- not supported in PFE or FEM, and mobile specific use case is not high priority.
