### ISSUE TITLE
Bullet points in Tutorial can break the mobile app

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#285]
In order to fix an issue, we need to be able to reproduce it. To give us the best chance of reproducing your issue, please follow these steps:

1. Please check that you currently have the latest mobile app version (2.6.1 as of July 2, 2019) installed. If not, please update.

In your issue, please include:

1. The version of Android or iOS that you are testing on.

Android Google Pixel 3

2. The device that you are testing on (for example, iPhone 7 or Samsung Galaxy s9)
3. What you did. Example: “I navigate to Floating forests, click the “field guide” button, then click on one of the options.”

Working with https://www.zooniverse.org/lab/5199/tutorial (Science Scribbler) mobile workflow. It was crashing the app. It turns out their 4th slide had poorly formatted bullet points in it, that were causing the problem. 

But even when correctly formatted (in terms of the markdown), bullet point lists (and enumerated lists) in the mobile app tutorial look funny (the bullet point is in the middle of the paragraph, rather than at the start like you'd expect). 

Not a major bug and for now we'll just recommend users don't use bulleted lists in their tutorials for mobile enabled workflows. 

But posting the issue here so that 6+ months from now, if we have FTE mobile dev support, we'll look to fix. 

4. What you expected to happen. Example: “I expected the option to open with a detail screen.”
5. The actual behavior.  Example: “The app crashed.”
6. Please include, if relevant, what particular projects or workflows it is happening on.
7. Please include whether you were logged in or logged out, acting as a guest user. If the issue has to do with a particular project or workflow, please try logging in and out and see if the issue persists in both cases.

**Comment by lcjohnso** [comment]
While crashing behavior has stopped, the original effect and current poor formatting is connected to Markdown library. For similar odd Markdown behavior, see #412

**Comment by lcjohnso** [comment]
No issue persists in version 2.11, likely due to #464; closing.
