### ISSUE TITLE
Can't use UI after clicking subject metadata links for 'in browser experience' projects

### ISSUE THREAD

**Issue by camallen** [zooniverse/mobile#286]
The 'in browser experience' projects loses interactivity with the subject metadata modal after clicking an external link from the subjects metadata.

1. Using Android 7.0
2. Moto G4 plus
3. Using an 'in browser experience' project (Galaxy Zoo) and after classifying I access talk. I then i click on a subjects metadata and click the link to SDSS/Decals. This launches the link in my phone default browser (out of app).
4. I expect to return and be able to interact with( close) the subject metadata modal after visiting the external link.
5. After returning to the app from the launched browser, I can't close the subject metadata modal using the ('X') button, i can only click the back button ('<') to get the app to respond.
6. Galaxy Zoo main project, not the special mobile one (i.e. in the 'in browser experience').
7. Tried both logged in and logged out (guest), issue persists with both states.

**Comment by lcjohnso** [comment]
Closing -- in browser experience has been deprecated.
