### ISSUE TITLE
Already seen banners on particular mobile projects

### ISSUE THREAD

**Issue by camallen** [zooniverse/mobile#289]
Originally reported via https://www.zooniverse.org/talk/739/1153260

All subjects are marked with already seen banners once the first 4/5 subjects are classified.

This only impacts on workflows with configuration directive `subject_queue_page_size = 4`. I.e. science scribbler team reported this. It might only happen on swipe card workflows as well.

Noting that i've checked the selection APIs and they aren't returning seen images in any subject requests.

I was using Zooniverse App v2.6.2

1. Using Android 7.0
0. Moto G4 plus
0. Navigate to science scribbler (or similarly configured workflow) and swipe classify some images
0. I get new subjects not seen images
0. The list of subjects is a repeat of what i've recently classified
0. Science scribbler mobile workflow, though it should happen on any workflow with `workflow.configuration['subject_queue_page_size'] = 4`
0. Logged in user and logged out.

**Comment by lcjohnso** [comment]
Closing; refer to #288
