### ISSUE TITLE
Missing icon for Social Science project category

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#292]
On iPhone 6s with iOS 13.1.3 using version 2.6.1 of the iOS app, the icon for social science is not showing.

Behavior: icon for social science is a question mark
![issue_missing_icon](https://user-images.githubusercontent.com/2006101/67595673-d2df9300-f72c-11e9-8079-9fdfbfe49f3e.png)

Expected (similar; here from desktop projects page):
![Screen Shot 2019-10-25 at 1 33 22 PM](https://user-images.githubusercontent.com/2006101/67595644-cb1fee80-f72c-11e9-8fef-f7565c996aa3.png)

Behavior is same whether logged in or not.

**Comment by lcjohnso** [comment]
I'm still seeing this issue -- now for 2.7.0 version of app on iPhone 6s running iOS 13.6.1

**Comment by chelseatroy** [comment]
I'm really struggling to repro this. This is on a 6s running 13.6.1:

<img width="385" alt="Screen Shot 2020-10-07 at 2 45 02 PM" src="https://user-images.githubusercontent.com/5744164/95379966-affdae80-08ab-11eb-9868-70ed3cf0bed0.png">

**Comment by lcjohnso** [comment]
It's possible another dependency update has fixed this?  My app is currently 2.7.0 and OS is 13.6.1 and I'm still seeing it, but this next release seems significant enough such that it might be fixed in the current dev build.

Because you can't replicate the issue, I'm happy to put this on hold to see whether or not to close it post-release.
