### ISSUE TITLE
Project appearing twice in a single discipline 

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#295]
Snapshot Enonkishu is appearing twice in the Biology discipline of the app. This was initially brought to our attention via a [ticket](https://zooniverse.freshdesk.com/a/tickets/1561). 

We've dealt with this before in #272, and we may be experiencing a similar issue here with the same project being returned from different calls in the [project action](https://github.com/zooniverse/mobile/blob/master/src/actions/projects.js).

**Comment by chelseatroy** [comment]
How do we repro this?

**Comment by lcjohnso** [comment]
No issue persists in version 2.11; closing.
