### ISSUE TITLE
In the swiping workflow, I can accidentally grab hold of the side menu if I grab the right most side of an image and try swiping to the left.

### ISSUE THREAD

**Issue by chelseatroy** [zooniverse/mobile#297]
In order to fix an issue, we need to be able to reproduce it. To give us the best chance of reproducing your issue, please follow these steps:

Please check that you currently have the latest mobile app version (2.6.1 as of July 2, 2019) installed. If not, please update.
In your issue, please include:

1. The version of Android or iOS that you are testing on: iOS 13
1. The device that you are testing on (for example, iPhone 7 or Samsung Galaxy s9): iPhone X Simulator
1. What you did.
I went to a swipe project in citizen science mode, grabbed the item to swipe, and dragged until my cursor/finger was over the menu button in the upper right hand corner. This dragged out the menu while I was still dragging the swipe item around.

**Comment by wgranger** [comment]
This was closed in #300
