### ISSUE TITLE
Crashing Bug: Double Submit

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#310]
There's a crashing bug in the app when someone presses the "submit" button quickly. The app will turn to a white screen.

**To Replicate:**
Open the Mapping Historic Skies app, which should be in museum mode. Start pressing the "submit" button quickly, and the screen should go all white. The app will need to be rebooted to continue.

**Comment by chelseatroy** [comment]
Fixified :) https://github.com/zooniverse/mobile/pull/311

**Comment by wgranger** [comment]
For context, this is the error we're experiencing. 

![Screen Shot 2019-12-04 at 11 31 40 AM](https://user-images.githubusercontent.com/14099077/70166105-ba4a8d00-1689-11ea-8db1-0c07ecc1ae50.png)
