### ISSUE TITLE
Tutorial is Crashing the App

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#313]
Reported via Slack with PH beta (project 8297). The tutorial is currently crashing the app. The may be related to the presence of tutorial images/icons, or it could be something new entirely.

**Comment by wgranger** [comment]
Issues noted:

- Project 8297 (Planet Hunters TESS Mobile)
- Same answer 'Discard' and 'Discard' showing up when swiping left and right
- Same behavior exists on GZ, and reloading the workflow may clear issue

**Comment by lcjohnso** [comment]
No issue persists in version 2.11; closing.
