### ISSUE TITLE
Should we remove the webview?

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#323]
The impetus for this conversation is a recent [Talk post](https://www.zooniverse.org/talk/17/1456199), which spawned a [PFE issue](https://github.com/zooniverse/Panoptes-Front-End/issues/5732)

The error noted in that post above occurs in the webview but not the mobile Safari browser. Although the fix for that issue may or may not lie in PFE, this brings up why we are using `Webview` and if we should move towards opening the project in the browser. Perhaps it may be time to drop webview for a few reasons:

- Webview was initially used when the app was new and we didn't have many "mobile-friendly" workflows available, which is no longer the case
- `Webview`, imported directly from `react-native` as we currently use in the app, is deprecated in lieu of the [react native community version](https://github.com/react-native-community/react-native-webview)
- Dragging by finger moves the page in a webview, but not in mobile PFE
- Sometimes, when reporting bugs via Freshdesk or TAlk, users are confused as to which workflows are powered by the app and which are actually opened in PFE
- The app already uses the term "in-browser experience," so it does not seem jarring to then open a project in a mobile browser

**Comment by lcjohnso** [comment]
Example of issue related to `Webview` tech: https://github.com/zooniverse/mobile/issues/286

**Comment by chelseatroy** [comment]
We stopped displaying projects that aren't mobile-friendly in the mobile app now, so we don't need to change the behavior of the webview. Instead, we can strip it out of the app entirely. 

I'll open a new issue to that effect.
