### ISSUE TITLE
GIF images not playing / animating on Android

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#332]
Reports from the Catalina Outer Solar System Survey project (Talk thread [here](https://www.zooniverse.org/projects/fulsdavid/catalina-outer-solar-system-survey/talk/3549/1578507)) state that GIF format subjects are not animating on Android from within Zooniverse mobile app.

**Expected Behavior:** subjects animate through multiple frames (4 for the case of Catalina OSSS project).  See also web version as example: https://www.zooniverse.org/projects/fulsdavid/catalina-outer-solar-system-survey/classify

**Actual Behavior (on Android):** only a single frame is shown; no animation or cycling between frames.

Does not work on Android 10 / Zoo App Android version 2.6.8
Works on iPhone 6s / iOS 13.6.1 / Zoo App 2.7.0

**Is this a bug fix or an enhancement?**  I've initially classified as bug because the animation seems to be working out of the box for iOS.  However, if significant work is needed to update the player on the Android side to get GIFs to work, then please reclassify as enhancement and lower in priority.

**Comment by trouille** [comment]
Note: related to NASA efforts.

**Comment by lcjohnso** [comment]
closed by #339
