### ISSUE TITLE
Improve Project Display: Selection + Ordering

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#337]
The current procedure that volunteers must follow to select projects and workflows to work on in the mobile app is difficult and time consuming: many projects and workflows shown are "out of data", forcing volunteers to search through long lists of projects to find one where their effort is wanted.

**Current Behavior:** The mobile app displays all active, mobile-enabled project + workflow combinations.  Ordering of projects within category-specific view appears to be alphabetical based on project name.  Also, the app's "show all workflows" setting that adds a "In-Browser Experience" section listing non-mobile projects is True by default.

**Proposed Behavior - Major Change Version:** Do not show projects for which all its workflows are out of data.  Equivalent to how "paused" projects (where all active workflows are complete / out of data) are moved to a separate page on the PFE projects page.  Note that the implementation to achieve this goal would necessarily be more complex than filtering projects based on Active vs. Paused status, as there are many cases where a project is Active due to non-mobile workflows, but should be Paused from a mobile-only perspective.  But it appears that there is already logic to decide whether or not to display an "out of data" flag on the project, so perhaps it would be possible to choose not to displays these projects at all.

**Proposed Behavior - Minor Change Version:** Sort projects in each category-specific view so projects with data to be classified (are *not* out of data) appear at the top of the list for best visibility.

**Proposed Behavior - additional change regarding in-browser options:** Set default for "Show all workflows" setting to False in order to restrict the mobile app for use with mobile-friendly workflows only.  Pro: focuses app usage to mobile-specific use case.  Con: new setting would reduce the number of available projects shown in the app.

I'm interested to hear feedback and concerns on this suggestion.
cc: @beckyrother @trouille @chelseatroy 

Related & supersedes: https://github.com/zooniverse/mobile/issues/178

**Comment by beckyrother** [comment]
I think the finished projects have been left on the app because there aren't a ton of projects currently available to look at; if that's changed it makes sense to remove them from the project list. 

At the least we should absolutely float projects with data to the top of the list. It looks like it's just alphabetical right now, so it could be 1 alphabetical with data, followed by 2 alphabetical without data. 

For later design work, a tab could be added to either show all projects or switch to viewing completed projects. Adding a note for #338

**Comment by lcjohnso** [comment]
But because we generally want to drive traffic to projects that currently need help, I'm continuing to advocate for keeping them off the app's project options.  I really like @beckyrother's idea of adding a switch so users can choose to view those projects if desired.

I agree that the lack of active projects / low count of projects is still a concern, and I appreciate that clicking into an empty lists seems like a waste.  But perhaps the solution to that issue would be to filter out categories with no active project entries.

**Comment by lcjohnso** [comment]
Also connect / relevant to decision about displaying in-browser options: Will's Issue #323 highlights that the `Webview` tech is starting to fall behind and volunteers would be better served by using a browser app rather than via `Webview` in the Zooniverse app.  To me this argues for not only changing the default to *not* show non-app project choices, but also potentially removing the `Webview` components completely.

**Comment by trouille** [comment]
Great that you see a way forward to be able to sort projects w/in a list to show ones with active data first. 

Good point on user experience if a category goes missing. If straightforward to put a placeholder card that says something to the effect of 'all projects out of data', that would be good. But first/easiest step is to just have continue to have the existing list (of 'out of data' projects). And at least for categories where there are projects with active data, the user will see the pattern that those get shifted to the top of the list.

**Comment by beckyrother** [comment]
Agreed that the categories should stay visible. A fix to this would be to add a count on the category card that shows the number active vs the total number of projects: 

![image](https://user-images.githubusercontent.com/1392130/94584009-b785dd80-0243-11eb-878e-8f75780e036a.png)
