### ISSUE TITLE
Improve Project Display: create "All Projects" category

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#338]
**Current Behavior:** The mobile app home page provides a list of project categories for volunteers to choose from as a first step to finding a project to work on.  The current small number of active mobile-friendly (and not out of data) project / workflow options can make the search for a project to work on difficult, where the user may need to scroll through multiple different categories to find a project to work on.

**Proposed Solution:** Add an "All Projects" category toward the top of the home page (below recent and preview, but above individual categories) that would allow users to quickly scan all project choices.  Especially when combined with the filtering of "out of data" projects (see #337), this new option would streamline the process of selecting a project.

I'm interested to hear feedback and concerns on this suggestion.
cc: @beckyrother @trouille @chelseatroy

**Comment by beckyrother** [comment]
I love this idea and could see two tiers of design work for this:

1. Literally just add a button at the top of the category list with the Zooniverse icon in place of a category icon that says "All projects"

2. Take this opportunity to update category icons and the layout of this page to match the updated classify page layouts. Design to come! This is not urgent and I'd recommend just doing 1.

**Comment by beckyrother** [comment]
As a quick fix, "View all" button should be at the very top of the list and use the Zooniverse logo as the icon: https://projects.invisionapp.com/d/main#/console/20526296/432733397/preview
