### ISSUE TITLE
Push Notifications User Settings

### ISSUE THREAD

**Issue by robinschaaf** [zooniverse/mobile#34]
Note that this depends on:
https://github.com/zooniverse/Panoptes/issues/2006

But in the meantime, we can develop against the project_preferences.email_communications field.

When subscribed / unsubscribed, we should subscribe to the projects via "Interests" in pusher.  e.g. `pusher.nativePusher().subscribe(interestName: "donuts")`

There should also be a Notifications Settings screen in which users can update their settings.  Note that this will also have to update the interests with Pusher, which for now is native code.  Perhaps investigate react native "Native Modules" ?

http://facebook.github.io/react-native/releases/0.33/docs/native-modules-ios.html
- [x] Notifications settings screen
- [x] Add pusher subscriptions

**Comment by wgranger** [comment]
Closed via #28 and #90
