### ISSUE TITLE
Can't delete drawn rectangles on Android devices

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/mobile#341]
In order to fix an issue, we need to be able to reproduce it. To give us the best chance of reproducing your issue, please follow these steps:

1. Please check that you currently have the latest mobile app version (2.6.9 as of Dec 3, 2019) installed. If not, please update.
- this issue is on current `master` branch

In your issue, please include:

1. The version of Android or iOS that you are testing on. - API 29
2. The device that you are testing on (for example, iPhone 7 or Samsung Galaxy s9) - Pixel 3 and Pixel 2
3. What you did. Example: “I navigate to Floating forests, click the “field guide” button, then click on one of the options.”
- Navigate to drawing workflow, draw rectangles, click to delete mode, click "X" to delete rectangle
4. What you expected to happen. Example: “I expected the option to open with a detail screen.”
- I expected the rectangles to be deleted
5. The actual behavior.  Example: “The app crashed.”
- nothing happened, no crash, could submit/close and continue using app
6. Please include, if relevant, what particular projects or workflows it is happening on.
- https://master.pfe-preview.zooniverse.org/lab/1608/workflows/3437, or any drawing workflow
7. Please include whether you were logged in or logged out, acting as a guest user. If the issue has to do with a particular project or workflow, please try logging in and out and see if the issue persists in both cases.
- both

**Comment by lcjohnso** [comment]
@chelseatroy Is this issue closed by #320?

**Comment by mcbouslog** [comment]
This is subsequent to #320. The close button appears in a good place (thanks to #320), but touching it doesn't delete the rectangle as expected.

**Comment by lcjohnso** [comment]
@mcbouslog Got it -- thanks!
