### ISSUE TITLE
Bug: media items not displaying in option buttons of question task

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#374]
**What the app is supposed to do:** Display media items when included as part of label for option buttons of question task. Example (below): render small thumbnail example images as part of button label.
<img width="200" alt="desktop_buttons" src="https://user-images.githubusercontent.com/2006101/127675821-d52fe740-67b5-4ee5-bce4-a6593a7e48b7.png">

**What the app does instead:** App does not render markdown media items as expected and instead shows code. Example (below): shows markdown syntax for media item (e.g., `![alt text](URL)`).  I've only seen this behavior on iOS devices (iPhone, iPad); have not confirmed it is happening on Android.
<img width="200" alt="mobile_buttons" src="https://user-images.githubusercontent.com/2006101/127675810-ac1f95f0-61e6-49a6-b392-701d92201626.png">

**Exact steps to Reproduce**
1. Go to ~~NASA GLOBE CLOUD GAZE project. (Desktop URL = https://www.zooniverse.org/projects/nasaglobe/nasa-globe-cloud-gaze)~~ Cliff's Test Project (Desktop URL = https://www.zooniverse.org/projects/lcjohnso/lcj-test)
2. Click on ~~Cloud Cover Workflow~~ Mobile App Workflow
3. Scroll down to buttons for question task to see non-rendered Markdown code.

**UPDATE:** CLOUD GAZE team has decided to remove icon images in labels until this bug is fixed.  Therefore, for an example of the bug in action on a project/workflow, please see https://www.zooniverse.org/projects/lcjohnso/lcj-test/classify?reload=0&workflow=9813 and it's Mobile App workflow (accessible via Preview section for collaborators).  

**UPDATE:** Added workflow on Chelsea's staging test project (https://master.pfe-preview.zooniverse.org/projects/chelseatroy/project-with-all-mobile-workflow-types / https://master.pfe-preview.zooniverse.org/lab/1892) to reproduce behavior.  New workflow = 3514: https://master.pfe-preview.zooniverse.org/lab/1892/workflows/3514 and https://master.pfe-preview.zooniverse.org/projects/chelseatroy/project-with-all-mobile-workflow-types/classify?reload=1&workflow=3514

**Desktop (please complete the following information):**
- OS: iOS (so far)
- Device: iPhone and iPad, variety of OS versions

**Additional context**
- May be connected to #351 but unsure.
- Seems notable that media items that are describe via same Markdown syntax in Tutorial and Help Text boxes are correctly rendering -- seems this bug is specific to the button labels.

**Comment by camallen** [comment]
![Screenshot_20210730-164446](https://user-images.githubusercontent.com/295329/127678808-e1707f50-0eac-48e9-9f13-ab41102ba9a2.jpg)

I see the same on android so i assume the app can't handle the markdown links with media URLS in them they way the main site can.

**Comment by lcjohnso** [comment]
> I see the same on android so i assume the app can't handle the markdown links with media URLS in them they way the main site can.

However, note that markdown links **are** correctly rendered when included in tutorial text or help text.

**Comment by lcjohnso** [comment]
I edited the original bug description above, but here's an update: the CLOUD GAZE team has decided to remove icon images in labels until this bug is fixed.  Therefore, for an example of the bug in action on a project/workflow, please see https://www.zooniverse.org/projects/lcjohnso/lcj-test/classify?reload=0&workflow=9813 and it's Mobile App workflow (accessible via Preview section for collaborators). 

Please let me know if anyone needs collaborator status to access this project for testing purposes.

**Comment by chelseatroy** [comment]
Hi @lcjohnso. Maybe this is my oversight, but I have never been aware that including an image in the actual _answer choice buttons_ on the app was supposed to work. My recommendation, devoid of further context, would be to tell this team that this feature is not expected to work on the mobile app and put it on the roadmap for the future. Has this feature worked in the past?

**Comment by lcjohnso** [comment]
@chelseatroy -- 

I am not sure the image rendering in the buttons previously worked in the app.  My assumption is that markdown-based rendering would work for any text field, not unlike the tutorial and help text fields.  Based on the code, can you clarify whether the button text is known to behave differently (is this a bug or expected behavior?) and what level of difficulty it would be to add rendering ability to the button text (in the case this is an enhancement).

I told the CLOUD GAZE team that a fix could take some time (true for case of bug or enhancement), and in response to that, the thumbnail images were removed.  Therefore, the priority of the issue remains the same (not critical) but the clarifying information would help in regards to planning and communicating future effort.

**Comment by chelseatroy** [comment]
Indeed, I checked the code, and there are no markdown provisions in the Button implementation. This was never implemented to work like this. I have removed the "bug" label.
