### ISSUE TITLE
User avatar behaviour on project list

### ISSUE THREAD

**Issue by rogerhutchings** [zooniverse/mobile#39]
Avatar should shrink and moves up once past the fold in the project list view

**Comment by robinschaaf** [comment]
![iphone 6 copy 27](https://cloud.githubusercontent.com/assets/1033477/19523710/44eac6d2-9613-11e6-96f1-91b8fe68e918.png)
![iphone 6 copy 34](https://cloud.githubusercontent.com/assets/1033477/19523717/49476208-9613-11e6-8c0f-79bbba86e98a.png)

**Comment by beckyrother** [comment]
This needs more design thinking, will close and re-open a new issue when a solution is found.
