### ISSUE TITLE
bug on Android: Text alignment is off 

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#394]
**What the app is supposed to do:**

Text should be aligned w/in buttons

**What the app does instead:**

Text is off-center w/in buttons. 
Multiple lines of text within buttons has unexpected spacing. 

**Exact steps to Reproduce**
1. Go to Mobile app. Open Disk Detective project. 
2. Scroll down to see the text in the response options (and how they're out of alignment)
3. Scroll down to 'Submit' button and 'Field Guide' button to see how the text is out of alignment. 

**Screenshots**

![Screenshot_20220402-105357](https://user-images.githubusercontent.com/4975655/161391132-4dad98fc-70cd-40b8-ab14-c55fa305b83d.png)
![Screenshot_20220402-105336](https://user-images.githubusercontent.com/4975655/161391135-4d4d4dbb-6d8d-4d98-8915-10613f6970ef.png)

** (please complete the following information):**
- OS: [e.g. iOS]: Android
- Device: (example:we once had an icon problem that only appeared on the Pixel 2): Moto g power (2021)
- Version [e.g. 2.8.2]: Android v11

**Additional context**

**Comment by lcjohnso** [comment]
Potentially a Markdown issue -- for similar issue, see #412.

**Comment by lcjohnso** [comment]
Closed by #464
