### ISSUE TITLE
bug on Android: the 'no' 'yes' buttons are too short (they used to be bigger)

### ISSUE THREAD

**Issue by trouille** [zooniverse/mobile#395]
**What the app is supposed to do:**

The 'no' 'yes' buttons for the swipe task used to be taller. They are now shorter/less prominent. This makes it harder to use. 

**What the app does instead:**

The 'no' 'yes' buttons for the swipe task are shorter, harder to use. 

**Exact steps to Reproduce**
1. Go to mobile app. Click on Galaxy Zoo mobile
2. See the size of the no/yes buttons

**Screenshots**
![Screenshot_20220402-105955 (1)](https://user-images.githubusercontent.com/4975655/161391344-fe8434b7-7cc9-40f5-be85-4462427657e9.png)

**Desktop (please complete the following information):**
- OS: [e.g. iOS]: Android
- Device: (example:we once had an icon problem that only appeared on the Pixel 2): Moto g power (2021)
- Version [e.g. 2.8.2]: Android v11

**Additional context**

**Comment by trouille** [comment]
This appears to be fixed in the updated version (i.e., based on the testing I carried out today). Note: I"m on Android Google Pixel6a. 



![Image](https://github.com/zooniverse/mobile/assets/4975655/efad9c6d-2777-470c-87de-48555956cadd)

**Comment by lcjohnso** [comment]
Closed by #467
