### ISSUE TITLE
Reinstate Google Analytics

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#413]
As a Zooniverse team member, I should be able to access statistics on app use (e.g., project level accounting of time spent by volunteers), and the app should record this data (in a user-anonymous way) and send to Google Analytics for access by the Zooniverse team for producing usage reports for internal use and to provide aggregated statistics for project teams.

As part of #389 (and #402 + #404), Google Analytics + Firebase were removed due to an out-of-date `react-native-google-analytics-bridge` dependency.  Restore GA using modern library.

**Comment by lcjohnso** [comment]
Note that Analytics for Zooniverse Mobile was configured via Firebase -- login with android@zooniverse.org Google Account and see https://console.firebase.google.com/

**Comment by coryzoon** [comment]
Closing issue since all changes have been merged with master.
