### ISSUE TITLE
Styling Bug: tutorial slide positioning

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#415]
## What the app is supposed to do

As volunteer pages through tutorial slides (either by clicking "continue" button, L or R arrow next to page dots, or swiping on tutorial slide) each new page aligns with modal so it can be read in its entirety.

## What the app does instead

Tutorial slides are not correctly aligned in left-to-right direction when viewed (only partial text in view) for pages beyond the first page (could be an issue with how slides are advancing?).

**To reproduce:** visit Disk Detective project in app, start tutorial, swipe or hit continue to visit pages 2-4 which are all misaligned.

**Screenshots**
<img src="https://user-images.githubusercontent.com/2006101/189455931-d370cde2-ac7d-470a-81a5-76e2abdb2cc1.jpeg" width="300">

## Device Info
- OS: iOS
- Device: iPhone 13 Pro (OS=15.5)
- App Version: 2.9.1

**Comment by coryzoon** [comment]
https://github.com/zooniverse/mobile/pull/467 fixes this issue.
