### ISSUE TITLE
Update to the latest Panoptes client

### ISSUE THREAD

**Issue by eatyourgreens** [zooniverse/mobile#423]
https://github.com/zooniverse/mobile/blob/7ac9404509e8ea54a462d52e813e55be3fdd5573/package.json#L42

PJC v3.0.0-rc.0 was released in November 2019. The latest version is 4.1.1, which includes a few bug fixes.

**Comment by coryzoon** [comment]
@lcjohnso I actually upgraded this while completing the React Native upgrades. I upgrade all of the dependencies which included panoptes-client.

**Comment by lcjohnso** [comment]
Closed by #458
