### ISSUE TITLE
Allow video subjects on multi-answer question tasks

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#455]
As a volunteer, I want to submit classifications on multi-answer question tasks (not binary / swipe question tasks) where the subject media is a video. The app should render videos so I can view the subject and submit a classification.

Example Project: [Name that Neutrino!](https://www.zooniverse.org/projects/icecubeobservatory/name-that-neutrino)

Additional context: merged PRs for adding multiple answer question (#245) and adding video subjects (#389).

**Comment by lcjohnso** [comment]
Closed by #411

**Comment by lcjohnso** [comment]
Not sure why the above project wasn't working with latest feature work.

**Comment by mcbouslog** [comment]
On my Mobile Testing Project (production) the workflow "Multiple Question with Video Subjects" works as expected.
