### ISSUE TITLE
Do not show finished projects in app

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#459]
The Projects page on web divides projects into three categories corresponding to project state: active, paused, finished. While mobile tends to sort projects so those with data appear at the top, and those out of data afterward, finished projects are included (though typically sorted as part of the out-of-data group).  

Desired Behavior: filter out state = finished projects so they don't appear in the mobile app.

**Comment by trouille** [comment]
Just noting my agreement with this.

**Comment by lcjohnso** [comment]
closed by #478
