### ISSUE TITLE
Refactor Connect social app links

### ISSUE THREAD

**Issue by mcbouslog** [zooniverse/mobile#461]
In the main hamburger menu, there's a Connect section that lists social app links that needs updating. Remove Google+ , not sure about others. https://www.zooniverse.org/ 's footer only includes Twitter/X and Facebook.

**Comment by lcjohnso** [comment]
the "t" icon is tumblr, and links to dailyzooniverse.tumplr.com -- I'm OK with leaving that, but perhaps we want to standardize & match primary web footer choices.

cc: @seanmiller26

**Comment by lcjohnso** [comment]
Outcome from conversation on 2024-01-11 with @seanmiller26 -- until we've decided what social media services we plan to use / support (example: are we planning to continue using X/formerly-Twitter?), we should **remove all links/logos from the hamburger menu** for the time being. 

Removal work will take place as part of related menu revisions connected with resolving #497.

**Comment by lcjohnso** [comment]
Closing for now; can revisit when platform-level decisions re: social account are made.
