### ISSUE TITLE
Restructure the current homepage to be the new Project page

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/mobile#482]
in the future we will be incorporating the ERAS stats service. This will live on a new homepage.

We can keep the design of the current homepage but it shouldn't be the root page. Up for discussion if we want to restyle this page to match future efforts.

To help visualize the new structure of the app:

<img width="1000" alt="Screen Shot 2023-11-10 at 3 56 13 PM" src="https://github.com/zooniverse/mobile/assets/89043489/cacd5946-d9d0-4d70-ac19-38a44294058b">

**Additional context**

**Comment by lcjohnso** [comment]
I don't see a significant benefit from moving the projects page (project categories that each lead to a corresponding list of project cards) off of the homepage into a separate page. Without a strong motivation for separation between homepage and projects page, I don't think it is worthwhile to add an additional step between opening the app and working on a project.  Therefore, I also don't think a bottom navigation bar is needed (see #480). 

I fully supportive of revamping the homepage, including improving and expanding display of personal stats (see related: https://github.com/zooniverse/mobile/issues/265), and improving the display of project subcategory options -- for example, by separating and changing appearance of topic-based project filter buttons, in contrast to other broader category buttons (all projects, recent projects, preview). I think these improvements would have much greater positive impact than separating projects from the homepage.

**Comment by seanmiller26** [comment]
The decision has been made to shelve this idea until the homepage is more feature-heavy. At that point we may revisit separating the Project selection and whatever other content may live on the future homepage.
