### ISSUE TITLE
Bug with opening and closing Tutorials causing you to see subjects you have already classified.

### ISSUE THREAD

**Issue by PlanetJames** [zooniverse/mobile#488]
**What the app is supposed to do:**

After making some classifications in a workflow, opening and closing the Tutorial should return you to the subject you were currently classifying.

**What the app does instead:**

After making some classifications in a workflow, opening and closing the Tutorial causes you instead see the same exact subjects that you've already classified since going to the workflow (in order from the start, with subjects (correctly) having the "already seen!" label). This is both confusing (seeing the same subjects again would imply the subject set is fully classified) and frustrating as the only way to return it to normal is to exit and re-enter the workflow.

This happens regardless of workflow/project, whether you're signed in or not,  and whether you exit the Tutorial by way of Question tab or Continue button. I've only been able to test this on iOS (15.8), though it doesn't seem like an iOS-dependent bug.

**Exact steps to Reproduce**
1. In the Zooniverse Mobile app, click on a workflow.
2. Classify one or more subjects (let's call them subjects A, B, C...)
3. Click the Tutorial tab.
4. Exit the Tutorial, either by clicking the Question tab or by clicking the "Continue" / "Let's Go!" buttons.
5. See error (i.e. presented with previously classified subjects, in order beginning with subject A).

**Mobile**
- OS: iOS
- Device: iPhone
- Version 15.8

**Comment by coryzoon** [comment]
I was able to reproduce and fix the bug, but I could only reproduce when the workflow type was "swipe". @PlanetJames if you were able to reproduce this on a project/workflow that did not allow swiping could you let me know that project/workflow so I can investigate further?

**Comment by lcjohnso** [comment]
Noting some context: @PlanetJames is involved with the Galaxy Zoo project, and the Galaxy Zoo Mobile project uses swipe question tasks, so it is likely the behavior was noticed for a swipe workflow. 

Echoing Cory above -- @PlanetJames please let us know if you are above to produce this on any non-swipe workflow, but otherwise we will move forward under the assumption that this bug and issue is addressed by the fix in https://github.com/zooniverse/mobile/pull/502.

**Comment by PlanetJames** [comment]
Hi both, thanks for looking into this! I've just had a go and as you say, I have only been able to reproduce the issue with swipe workflows, so feel free to go ahead!

**Comment by lcjohnso** [comment]
Closed by #502
