### ISSUE TITLE
Google Analytics: human-readable page names

### ISSUE THREAD

**Issue by lcjohnso** [zooniverse/mobile#492]
As a Zoo Team Member, when I login to Google Analytics for the mobile app I should be able to view page view statistics according to project and workflow. The app should tag pages with useful, human-readable names (rather than current values, such as RNSScreen, UIViewController, MainActivity, etc) that allow at least project-level interpretation of volunteer activity on the app.

To clarify: while PFE includes custom events used to log detailed user behavior, the requested scope for this issue is _only_ top-level stats of projects and/or workflows.

**Comment by coryzoon** [comment]
Closing issue since the changes have been merged with master.
