### ISSUE TITLE
Feedback modal should auto close after x seconds - Museum mode

### ISSUE THREAD

**Issue by seanmiller26** [zooniverse/mobile#573]
I'd like the feedback modals to auto-close after x seconds (5?, 10?). And if possible, to not open a bigger can of worms for the time being, only apply this to Museum Mode enabled projects. 

This will be a useful feature for projects on the museum floor. We want a new museum patron to see a fresh subject as they approach the podium/kiosk. We don't want them to see a previous feedback modal from the last user's session.

**Comment by seanmiller26** [comment]
I think to allow enough time to read the feedback, we would want a value of around 10 seconds. Once this in place, we can better test it to find any outliers ie. really long feedback text.

This will be the actual project used in the new Adler exhibit: https://www.zooniverse.org/lab/22096/workflows/25356

Question: is there a way to enable this on mobile currently? Right now you must not have feedback on a project, but is there a workaround so we can test it on our devices?

**Comment by lcjohnso** [comment]
> Question: is there a way to enable this on mobile currently? Right now you must not have feedback on a project, but is there a workaround so we can test it on our devices?

@seanmiller26 https://github.com/zooniverse/Panoptes-Front-End/pull/7092 got merged and deployed on Monday, so the feedback check should be removed in the Lab for question tasks now -- try reloading the page, but report back if you are still having problems enabling for mobile.

**Comment by lcjohnso** [comment]
Closed by #572
