### ISSUE TITLE
Clicking links opens in native browser 

### ISSUE THREAD

**Issue by camallen** [zooniverse/mobile#95]
Clicking links like my user profile / settings opens the links in my mobile chrome browser but without any login session, etc but also in the mobile app. It seemed strange as i was logged out in chrome but logged in via web view. Haven't tested on any other devices.

**Comment by noahmalmed** [comment]
@camallen do you know if this is still an issue/ could you clarify the problem. I'm not quite sure what links you are referring to.

**Comment by camallen** [comment]
The links from the top right hamburger menus e.g. Home, about, etc. 

Seems they open just fine in the app now, i'm not seeing them open in my browser.
