### ISSUE TITLE
Clear Classification Counts Upon Signout

### ISSUE THREAD

**Issue by wgranger** [zooniverse/mobile#98]
<img width="157" alt="screen shot 2017-03-20 at 11 48 29 am" src="https://cloud.githubusercontent.com/assets/14099077/24111129/6fa4b1e0-0d63-11e7-9889-1be48e3e26a2.png">

I'm seeing a landing page that looks like this when I have logged out. This might have to do with some info being saved in local storage and not being cleared when the user has signed out. This is worth replication (sign out, continue as guest, and check landing page), because I have only checked this on the iOS emulator.

**Comment by robinschaaf** [comment]
Somehow I haven't been able to replicate this, although I have seen it in the past.  Something else may have fixed it.  If you see it again, could you try to see if you can replicate it?
Thanks!

**Comment by wgranger** [comment]
I will, but I believe this was a sessions issue that was fixed with #103
